#!/usr/bin/env node
// Detect drift between the authoritative auqw-guest-sdk (in a sibling
// ../auqw checkout's sdk/rust) and the vendored copy this repo builds
// guests against. The vendor dir persists only while guests still build
// on it, so drift means: SDK source changed without a vendor-sdk.sh
// refresh, or the crate version moved and a new vendor dir is due.
//
//   node tooling/vendor-check.mjs [--sdk <path>]
//   node tooling/vendor-check.mjs --check    # CI: fail on drift
//
// Compares the cargo package's file list + contents (Cargo.toml,
// Cargo.lock, src/**, build.rs) between sdk/rust and each
// vendor/auqw-guest-sdk-<version>/ dir. Drift on the version guests
// build against is an error; SDK source carrying a NEWER version than
// any vendor dir is a warning (a refresh is due but guests still
// build) — --check fails on both.
import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const arg = (name) => {
  const i = process.argv.indexOf(name);
  return i > 0 && i + 1 < process.argv.length ? process.argv[i + 1] : undefined;
};
const sdkPath = resolve(arg('--sdk') ?? join(ROOT, '..', 'auqw', 'sdk', 'rust'));
const checkOnly = process.argv.includes('--check');

const fail = (msg) => {
  console.error(`vendor-check: ${msg}`);
  process.exit(1);
};

if (!existsSync(sdkPath)) {
  if (checkOnly) fail(`SDK source not found at ${sdkPath} — pass --sdk <path>`);
  console.log('vendor-check: no sibling SDK checkout — nothing to compare');
  process.exit(0);
}

const readVersion = (manifestPath) => {
  const m = readFileSync(manifestPath, 'utf8');
  const name = m.match(/^name = "(.*)"$/m)?.[1];
  const version = m.match(/^version = "(.*)"$/m)?.[1];
  return { name, version };
};

const { name: sdkName, version: sdkVersion } = readVersion(join(sdkPath, 'Cargo.toml'));
if (sdkName !== 'auqw-guest-sdk') fail(`expected auqw-guest-sdk at ${sdkPath}, found ${sdkName}`);

const listFiles = (dir) =>
  execFileSync('git', ['-C', dir, 'ls-files', '--cached', '--others', '--exclude-standard'])
    .toString()
    .split('\n')
    .filter((f) => f && !f.endsWith('.crate'));

const cmpSemver = (a, b) => {
  const [as, bs] = [a, b].map((v) => v.split('.').map(Number));
  for (let i = 0; i < 3; i += 1) if (as[i] !== bs[i]) return as[i] - bs[i];
  return 0;
};

const vendorDirs = readdirSync(join(ROOT, 'vendor'))
  .filter((d) => d.startsWith('auqw-guest-sdk-'))
  .map((d) => ({ dir: join(ROOT, 'vendor', d), version: d.replace('auqw-guest-sdk-', '') }));
if (vendorDirs.length === 0) fail('no vendor/auqw-guest-sdk-<version> dir found');

let worst = 0; // 0 ok, 1 warn, 2 error
const report = (level, msg) => {
  worst = Math.max(worst, level);
  console.log(`${level === 0 ? 'ok' : level === 1 ? 'warn' : 'DRIFT'} — ${msg}`);
};

const matching = vendorDirs.filter((v) => v.version === sdkVersion);
if (matching.length === 0) {
  const newest = vendorDirs.reduce((a, b) => (cmpSemver(a.version, b.version) > 0 ? a : b));
  const cmp = cmpSemver(sdkVersion, newest.version);
  report(cmp > 0 ? 1 : 2, `SDK source is ${sdkVersion}; newest vendor dir is ${newest.version} — run tooling/vendor-sdk.sh`);
} else {
  const vendor = matching[0];
  const sdkFiles = listFiles(sdkPath);
  const vendorFiles = listFiles(vendor.dir);
  // The vendored Cargo.toml is cargo's normalized package form and
  // Cargo.lock is generated by `cargo package` — neither has a raw
  // source counterpart. Only src/** is byte-compared; the version pin
  // above covers Cargo.toml.
  const comparable = vendorFiles.filter((f) => f.startsWith('src/'));
  if (comparable.length === 0) fail(`no comparable source files under ${vendor.dir}`);
  let drifted = 0;
  let absent = 0;
  for (const f of comparable) {
    const sdkFile = join(sdkPath, f);
    if (!existsSync(sdkFile)) {
      absent += 1;
      continue;
    }
    if (readFileSync(sdkFile).equals(readFileSync(join(vendor.dir, f)))) continue;
    drifted += 1;
    report(2, `${f} differs between SDK source and vendor/auqw-guest-sdk-${vendor.version}`);
  }
  if (absent > 0) report(2, `${absent} vendored source files absent from SDK source`);
  const newInSdk = sdkFiles.filter((f) => f.startsWith('src/') && !vendorFiles.includes(f));
  for (const f of newInSdk) {
    report(2, `${f} exists in SDK source but not in vendor/auqw-guest-sdk-${vendor.version}`);
  }
  if (drifted === 0 && absent === 0 && newInSdk.length === 0) {
    report(0, `vendor ${vendor.version} matches SDK source ${sdkVersion} (${comparable.length} source files)`);
  }
}

process.exit(checkOnly && worst > 0 ? 1 : 0);
